name: Proof HTML
on:
  push:                
    branches: [ Abhyuday ]
  pull_request:         

jobs:
  proof-html:           
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run proof-html
        uses: anishathalye/proof-html@v2.2.0  
        with:
          directory: .        
          check_html: true    
          check_css:  true   
          check_favicon: false
